### NumPy（Numerical Python）
- Numpy是Python中最重要的科学计算库之一。
- 它提供了高效的多维数组对象（ndarray），并内置大量数学函数、线性代数运算、随机数生成和统计分析功能。
- 相比普通 Python 列表，NumPy在速度和内存效率上更有优势，是数据分析、机器学习和科学计算的基础工具。

In [ ]:
import numpy as np

### 1. 创建数组

In [ ]:
# 创建最简单的numpy数组

a_list = [1, 2, 3]

a = np.array(a_list)

a

In [ ]:
a_list * 2 

In [ ]:
a * 2 

In [ ]:
# 创建全零数组
b = np.zeros((2, 3))  # 2行3列的全零数组
b

In [ ]:
# 全1数组
c = np.ones((3, 2))  # 3行2列的全1数组
c

In [ ]:
# 单位矩阵
d = np.eye(3)  # 3x3单位矩阵
d

In [ ]:
# 确定步长的等差数列
e = np.arange(0, 10, 2)  # 从0到10，步长为2
e

In [ ]:
# 确定个数的等差数列
f = np.linspace(0, 1, 5)  # 从0到1，生成5个数
f

In [ ]:
# 定义数据类型
np.array([1,2,3], dtype=np.int32)      # 指定整型

In [ ]:
np.array([1.2,3.4], dtype=np.float32)  # 指定浮点型

In [ ]:
np.array([1+2j, 3+4j], dtype=np.complex64)  # 复数

In [ ]:
np.array([True, False], dtype=np.bool_)     # 布尔

In [ ]:
np.array(['2025-01-01'], dtype=np.datetime64)  # 日期

### 2. 数组特征

In [ ]:
d

In [ ]:
# 数组维度
d.shape    

In [ ]:
# 维度数
d.ndim

In [ ]:
# 元素总数
d.size

In [ ]:
# 数据类型
d.dtype

### 3. 数组运算

In [ ]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

In [ ]:
x + y       # [11, 22, 33]

In [ ]:
x - y       # [-9, -18, -27]

In [ ]:
x * y       # [10, 40, 90]  (逐元素相乘)

In [ ]:
x / y       # [0.1, 0.1, 0.1]

In [ ]:
x ** 2      # [1, 4, 9]     (幂运算)

In [ ]:
np.dot(x, y)  # 点积 (1*10 + 2*20 + 3*30 = 140)

### 4. 索引和切片

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

In [ ]:
A[0, 0]      # 1 (第一行第一列)

In [ ]:
A[:, 1]      # [2,5,8] (第2列)

In [ ]:
A[1, :]      # [4,5,6] (第2行)

In [ ]:
# 行：1，2，3；3排除在外
# 列：2，3，4；4排除在外
A[0:2, 1:3]  # 子矩阵 [[2,3],[5,6]]

In [ ]:
# 最近数字的位置
wanted_element = 7.8 
B = np.linspace(0, 10, 11)
B 

In [ ]:
idx = (np.abs(B - wanted_element)).argmin()
idx

In [ ]:
B[idx]

### 5. 数学函数

In [ ]:
np.sqrt([1,4,9])      # 平方根

In [ ]:
np.exp([0,1])         # e^x

In [ ]:
np.log([1, np.e])     # ln(x)

In [ ]:
np.log10([1, 10, 100]) # log10(x)

In [ ]:
np.sin(np.pi/2)       # 1.0
np.cos(0)          # 1.0
np.tan(np.pi/4)       # 1.0

In [ ]:
np.mean([1,2,3])      # 平均值 2.0

In [ ]:
np.median([1,2,3,4,4,8])  # 中位数

In [ ]:
np.std([1,2,3])       # 标准差

In [ ]:
np.sum([1,2,3])       # 和

In [ ]:
np.min([3,1,4])       # 最小值

In [ ]:
np.max([3,1,4])       # 最大值

### 6. 形状变换

In [ ]:
A1 = np.arange(6)       # [0,1,2,3,4,5]
A1 

In [ ]:
# 变形
A1.reshape(3,2) 

In [ ]:
A2 = np.array(
    [[0, 1, 2],
    [3, 4, 5]])
A2

In [ ]:
# 扁平化
A2.ravel()

In [ ]:
# 转置
A2.T                    

### 7. 合并与拆分

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
a, b

In [ ]:
# 垂直堆叠
np.vstack((a, b))

In [ ]:
# 水平堆叠
np.hstack((a, a))

In [ ]:
# 按行分割
np.split(a, 2, axis=0)  # 按行分割成2部分

In [ ]:
# 按列分割
np.split(a, 2, axis=1)  # 按列分割成2部分

In [ ]:
# 在指定轴上拼接多个数组 
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a, b 

In [ ]:
np.concatenate((a, b))

In [ ]:
# 二维数组拼接（按行）
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
a,b

In [ ]:
np.concatenate((a, b), axis=0)

In [ ]:
# 二维数组拼接（按列）
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
a,b

In [ ]:
np.concatenate((a, b), axis=1)

### 8. 随机数

In [103]:
# 均匀分布 [0,1)
np.random.rand(3,2)  # 3行2列

array([[0.12992703, 0.82895295],
       [0.6200832 , 0.96765876],
       [0.26847909, 0.92348916]])

In [104]:
# 标准正态分布
np.random.randn(3,2)  # 3行2列

array([[-1.39725267,  0.00782591],
       [-1.05851044, -0.30734452],
       [ 0.22679692,  0.84782686]])

In [105]:
# 0-9 随机整数
np.random.randint(0, 10, 5)  # 5个随机整数

array([2, 0, 3, 4, 3])

In [106]:
# 0-9 随机整数
np.random.randint(0, 10, (3,2))  # 3行2列的随机整数

array([[0, 9],
       [2, 0],
       [9, 8]])

### 9. 条件筛选

In [96]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [100]:
a[a >= 2]   

array([2, 3, 4, 5])

In [101]:
# 偶数的索引
idx = np.where(a%2==0) 
idx

(array([1, 3]),)

In [102]:
a[idx]

array([2, 4])